### ISSUE TITLE
InsertDocument is changing list type

### ISSUE THREAD

**Issue by bigdnf** [xceedsoftware/DocX#155]
I'm trying to use InsertDocument to insert some document containing two types of lists - first there is some unnumbered list and then is numbered. After inserting all list are numbered. Is there any way to insert document just like it is in original?

**Comment by XceedBoucherS** [comment]
Hi,
This is already fixed in v1.2 an up.

Current versions are : 
-DocX v1.1
-Xceed Words for .NET v1.3

"DocX" is always a couple of versions behind "Xceed Words for .NET", and "DocX" as less features. You can buy "Xceed Words for .NET", always have the latest version (with support), or wait for releases of "DocX". Here is the link to "Xceed Words for .NET" : https://xceed.com/xceed-words-for-net/
Thanks.

**Comment by bigdnf** [comment]
Ok I will check 1.3. Is there any plans for updating github sources till end of the year?

**Comment by XceedBoucherS** [comment]
"DocX" and "Xceed Words for .NET" always go 1 version up at about the same time.
Next release should be around new year's day.
