### ISSUE TITLE
Bookmark memory issues?

### ISSUE THREAD

**Issue by EenPOOL** [xceedsoftware/DocX#219]
When I try to read the bookmarks, it takes forever in the latste version (1.1.0)

var document = Docx.Load(pathToWordDocument)
var bookmarks = document.Bookmarks; // this line takes at least a minute, with just 20 bookmarks

My solution for this moment: use version 1.0.0.22, this one reads the bookmarks pretty instantly

**Comment by XceedBoucherS** [comment]
Hi,
This is already fixed in v1.4.
-Users of "Xceed Words for .NET" currently have v1.4. (you can get it here : https://xceed.com/xceed-words-for-net/).
-Users of "DocX" currently have v1.1

"DocX" is the free version of "Xceed Words for .NET", is always some versions behind and have less features.
Thank you.
